# This is the default configuration file
# Please use it as reference only
#
# If you want to modify the values please
# create a "config.local.yml" in the same folder
vm_ip: 192.168.99.100
vm_name: matomo
vm_type: minimal

server_name: dev.matomo.io
source: ../matomo
source_device_detector: ../device-detector
source_searchengine_social_list: ../searchengine-and-social-list
source_matomo_tracker: ../php-tracker

mysql_database: matomo
mysql_password: matomo
mysql_username: matomo

plugin_glob: ../{matomo-plugin,plugin}-*/
plugin_pattern: plugin-([a-zA-Z]*)$
